
destination: ./_site
includes:    ./_includes

pygments:    true
markdown:    rdiscount
permalink:   /:title.html

paginate: 10
paginate_path: "/page:num"

# base_url: http://paulstamatiou.com
baseurl: /colada
name: Colada
description: "Regular dispatches covering Tech and Web development brought by Matthias Vandermaesen."
root_desc: "colada.be - Dispatches on Tech and Web development"
url: "http://www.colada.be"

exclude: ['README.md', 'config.rb', 'node_modules', 'Gruntfile.js', 'package.json']

