highlighter: pygments
markdown:    kramdown
permalink:   /:title.html

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 10
paginate_path: "/page:num"

name: Colada
description: "Regular dispatches covering Tech and Web development brought by Matthias Vandermaesen."
root_desc: "colada.be - Dispatches on Tech and Web development"

exclude: ['README.md', 'config.rb', 'node_modules', 'Gruntfile.js', 'package.json', 'CNAME', 'Gemfile.lock', 'Gemfile', 'sass']
