multiviews: true
#only works with https://github.com/stammy/jekyll, explained below

source:      .
destination: ./www
includes:    ./_includes

pygments:    true
markdown:    rdiscount
permalink:   /:title.html

# base_url: http://paulstamatiou.com
base_url: /
name: Colada
description: "Regular dispatches covering Tech and Web development brought by Matthias Vandermaesen."
root_desc: "colada.be - Dispatches on Tech and Web development"
url: "http://www.colada.be"

rdiscount:
  extensions: []

exclude: ['Rakefile', 'README.markdown', 'config.rb', 'node_modules', 'Gruntfile.js', 'package.json']

