encoding: utf-8

markdown:    kramdown
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'

permalink:   /:title.html

title: Matthias Vandermaesen
description: "Dispatches from my digital life."

paginate: 50
paginate_path: "/page/:num"

exclude:
  - README.md
  - CNAME
  - Gemfile.lock
  - Gemfile
keep_files:
  - .git

defaults:
  css: /css/style.css

lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

