baseURL = "https://www.colada.be/"
locale = "en-us"
title = "Matthias Vandermaesen"

ignoreFiles = [
  "^migration\\.md$",
  "^README\\.md$",
]

[uglyURLs]
  posts = true

disableKinds = ["taxonomy", "term", "section"]

[pagination]
  pagerSize = 50
  path = "page"

[params]
  description = "Dispatches from my digital life."

[permalinks]
  posts = "/:slug"

[outputs]
  home = ["HTML", "RSS"]
  taxonomy = []
  term = []
  section = []

[outputFormats.RSS]
  mediaType = "application/rss+xml"
  baseName = "feed"

[services]
  [services.rss]
    limit = 10

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = false
    noClasses = false
